version = 1

test_patterns = ["tests/**"]

exclude_patterns = [
  "vendor/**",
  "bootstrap/**",
  "config/**",
  "database/**",
  "public/**",
  "storage/**",
  "resources/**"
]

[[analyzers]]
name = "php"
enabled = true
